batch_size: 6
linear_probing: false
lora: true
lora_checkpoint_dir: ./.checkpoints/lora
lora_layer_idxs:
  audio: null
  text: null
  vision: null
lora_modality_names:
- vision
- text
- audio
lora_rank: 4
lr: 5.0e-06
max_epochs: 500
momentum_betas:
- 0.9
- 0.95
num_workers: 10
seed: 42
self_contrast: false
temperature: 0.07
weight_decay: 0.0001
